name: chemsmart
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - pymol-open-source=3.1.0
  - ffmpeg=7.1.1  # movie support for pymol
  - openbabel          # includes Python bindings on conda-forge
  - make               # required by CI and local Makefile (Windows has no system make)
  - pip
