[build-system]
requires = ["setuptools>=64", "setuptools_scm>=8"]
build-backend = "setuptools.build_meta"


[project]
name = "chemsmart"
dynamic = ["version"]
requires-python = ">=3.10"
dependencies = [
    "numpy>=1.17.0",
    "scipy>=1.3.1",
    "matplotlib>=3.1.0",
    "click>=8.1.5",
    "ase==3.23.1b1",
    "pyyaml",
    "hypothesis",
    "statsmodels",
    "pytrr",
    "basis_set_exchange",
    "pytest",
]


[project.scripts]
pyatoms = "chemsmart.cli.main:main"


[project.optional-dependencies]
docs = ["sphinx", "sphinx_rtd_theme", "pillow"]
test = ["pytest>=5.0.0", "pytest-mock>=3.3.0", "pytest-xdist>=1.30.0"]


[tool.setuptools]
# Needs to be false, if not the excluded packages in packages.find are still included
# https://github.com/pypa/setuptools/issues/3260
include-package-data = false


[tool.setuptools.packages.find]
exclude = ["chemsmart.tests*",
	  "chemsmart.scripts*"]


[tool.setuptools.package-data]
"chemsmart.settings.projects.templates" = ["*.yaml"]


[tool.setuptools_scm]
#version_file = "chemsmart/_version.py"
#version_scheme = "release-branch-semver"

[tool.pytest.ini_options]
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
]

