"""
Generator for Gaussian External calculator scripts using ASE.

This module provides ASEExternalCalculatorScript, which writes a
standalone Python script that Gaussian invokes via the External= keyword.
The generated script reads Gaussian's external-format input file, runs an
ASE calculator, and writes the energy (and optionally gradient) back in
Gaussian's external-format output file.

Gaussian External interface
---------------------------
Gaussian calls the script as::

    <script> [extra_args] layer InputFile OutputFile MsgFile FChkFile MatElFile

The six standard parameters are always the **last** six arguments.

Input file format (all values in atomic units)::

    natoms  deriv_order  charge  spin          (4I10)
    atomic_num  x  y  z  mm_charge            (I10, 4F20.12) × natoms

  - Positions in Bohr.
  - deriv_order: 0 = energy only, 1 = energy + gradient.

Output file format (all values in atomic units)::

    energy  dip_x  dip_y  dip_z              (4D20.12)
    dE/dX   dE/dY  dE/dZ                     (3D20.12) × natoms  [if deriv≥1]

  - Energy in Hartree.
  - Dipole in Debye (may be zero).
  - Gradient (dE/dX) in Hartree/Bohr; note gradient = −force.
"""

import inspect
import logging
import os
import stat
import textwrap

logger = logging.getLogger(__name__)

# ── Unit-conversion constants (atomic units ↔ ASE units) ──────────────────
_BOHR_TO_ANG = 0.529177210903
_EV_PER_HA = 27.211386245988
# Gradient conversion: 1 Ha/Bohr = EV_PER_HA / BOHR_TO_ANG  eV/Å
# So:  gradient[Ha/Bohr] = gradient[eV/Å] × BOHR_TO_ANG / EV_PER_HA
_GRAD_CONV = _BOHR_TO_ANG / _EV_PER_HA  # multiply eV/Å gradient by this


# ── Script template (code-generation path) ────────────────────────────────
_SCRIPT_TEMPLATE = textwrap.dedent(
    '''\
    #!/usr/bin/env python
    """
    Gaussian External calculator script — generated by chemsmart.

    Invocation::

        {script_name} [extra_args] layer InputFile OutputFile MsgFile FChkFile MatElFile

    The six standard Gaussian External parameters are always the last six
    arguments.  Any leading arguments are ignored (they are consumed by
    Gaussian's External dispatch mechanism).
    """

    import sys
    import os

    import numpy as np
    from ase import Atoms
    {calc_import}

    # ── Unit-conversion constants ──────────────────────────────────────────
    BOHR_TO_ANG = 0.529177210903
    EV_PER_HA = 27.211386245988
    # gradient[Ha/Bohr] = gradient_eV_Ang × BOHR_TO_ANG / EV_PER_HA
    GRAD_CONV = BOHR_TO_ANG / EV_PER_HA


    def _read_input(filename):
        """
        Parse a Gaussian External input file.

        Returns
        -------
        tuple
            (natoms, deriv_order, charge, spin, atomic_numbers, positions_ang)
            where positions_ang is in Angstrom.
        """
        with open(filename) as fh:
            lines = fh.readlines()
        header = lines[0].split()
        natoms = int(header[0])
        deriv_order = int(header[1])
        charge = int(header[2])
        spin = int(header[3])
        atomic_numbers = []
        positions_ang = []
        for line in lines[1 : natoms + 1]:
            parts = line.split()
            atomic_numbers.append(int(float(parts[0])))
            positions_ang.append(
                [
                    float(parts[1]) * BOHR_TO_ANG,
                    float(parts[2]) * BOHR_TO_ANG,
                    float(parts[3]) * BOHR_TO_ANG,
                ]
            )
        return natoms, deriv_order, charge, spin, atomic_numbers, positions_ang


    def _write_output(filename, energy_ha, gradient_ha_bohr=None):
        """
        Write a Gaussian External output file (energy + optional gradient).

        Parameters
        ----------
        filename : str
            Path to the output file Gaussian will read.
        energy_ha : float
            Total energy in Hartree.
        gradient_ha_bohr : array-like or None
            Gradient (dE/dX) in Hartree/Bohr, shape (natoms, 3).
            Note: gradient = −force.  Pass None for energy-only jobs.
        """
        with open(filename, "w") as fh:
            # Energy and dipole (dipole set to zero — not provided).
            fh.write(
                f"{{energy_ha:20.12E}}{{0.0:20.12E}}{{0.0:20.12E}}{{0.0:20.12E}}\\n"
            )
            if gradient_ha_bohr is not None:
                for gx, gy, gz in gradient_ha_bohr:
                    fh.write(f"{{gx:20.12E}}{{gy:20.12E}}{{gz:20.12E}}\\n")


    def main():
        # The six standard Gaussian External parameters are always last.
        if len(sys.argv) < 7:
            sys.stderr.write(
                f"Usage: {{sys.argv[0]}} [extra_args] "
                "layer InputFile OutputFile MsgFile FChkFile MatElFile\\n"
            )
            sys.exit(1)

        _layer = sys.argv[-6]
        input_file = sys.argv[-5]
        output_file = sys.argv[-4]
        msg_file = sys.argv[-3]
        # fchk_file and matel_file are not used for ASE-based calculations.

        try:
            (
                natoms,
                deriv_order,
                charge,
                spin,
                atomic_numbers,
                positions_ang,
            ) = _read_input(input_file)

            atoms = Atoms(numbers=atomic_numbers, positions=positions_ang)

            # ── Instantiate the calculator ─────────────────────────────────
            {calc_init}
            atoms.calc = calc

            # ── Compute energy ─────────────────────────────────────────────
            energy_ev = atoms.get_potential_energy()
            energy_ha = energy_ev / EV_PER_HA

            # ── Compute gradient (if requested) ────────────────────────────
            gradient_ha_bohr = None
            if deriv_order >= 1:
                # ASE forces = −gradient; gradient = −forces.
                forces_ev_ang = atoms.get_forces()
                gradient_ha_bohr = -forces_ev_ang * GRAD_CONV

            _write_output(output_file, energy_ha, gradient_ha_bohr)

            with open(msg_file, "w") as fh:
                fh.write(
                    f"{calc_class_name} completed. "
                    f"Energy = {{energy_ha:.8f}} Ha\\n"
                )

        except Exception:
            import traceback

            with open(msg_file, "w") as fh:
                fh.write(
                    "ERROR in Gaussian External ASE script:\\n"
                    + traceback.format_exc()
                )
            raise


    if __name__ == "__main__":
        main()
    '''
)

# ── Pickle-based variant (fallback) ───────────────────────────────────────
_PICKLE_TEMPLATE = textwrap.dedent(
    '''\
    #!/usr/bin/env python
    """
    Gaussian External calculator script (pickle-based) — generated by chemsmart.
    """

    import sys
    import os
    import pickle

    import numpy as np
    from ase import Atoms

    BOHR_TO_ANG = 0.529177210903
    EV_PER_HA = 27.211386245988
    GRAD_CONV = BOHR_TO_ANG / EV_PER_HA

    _PICKLE_FILE = os.path.join(os.path.dirname(__file__), "{pickle_name}")


    def _read_input(filename):
        with open(filename) as fh:
            lines = fh.readlines()
        header = lines[0].split()
        natoms = int(header[0])
        deriv_order = int(header[1])
        charge = int(header[2])
        spin = int(header[3])
        atomic_numbers = []
        positions_ang = []
        for line in lines[1 : natoms + 1]:
            parts = line.split()
            atomic_numbers.append(int(float(parts[0])))
            positions_ang.append(
                [
                    float(parts[1]) * BOHR_TO_ANG,
                    float(parts[2]) * BOHR_TO_ANG,
                    float(parts[3]) * BOHR_TO_ANG,
                ]
            )
        return natoms, deriv_order, charge, spin, atomic_numbers, positions_ang


    def _write_output(filename, energy_ha, gradient_ha_bohr=None):
        with open(filename, "w") as fh:
            fh.write(
                f"{{energy_ha:20.12E}}{{0.0:20.12E}}{{0.0:20.12E}}{{0.0:20.12E}}\\n"
            )
            if gradient_ha_bohr is not None:
                for gx, gy, gz in gradient_ha_bohr:
                    fh.write(f"{{gx:20.12E}}{{gy:20.12E}}{{gz:20.12E}}\\n")


    def main():
        if len(sys.argv) < 7:
            sys.stderr.write(
                f"Usage: {{sys.argv[0]}} [extra_args] "
                "layer InputFile OutputFile MsgFile FChkFile MatElFile\\n"
            )
            sys.exit(1)

        _layer = sys.argv[-6]
        input_file = sys.argv[-5]
        output_file = sys.argv[-4]
        msg_file = sys.argv[-3]

        try:
            (
                natoms,
                deriv_order,
                charge,
                spin,
                atomic_numbers,
                positions_ang,
            ) = _read_input(input_file)

            atoms = Atoms(numbers=atomic_numbers, positions=positions_ang)

            with open(_PICKLE_FILE, "rb") as fh:
                calc = pickle.load(fh)
            atoms.calc = calc

            energy_ev = atoms.get_potential_energy()
            energy_ha = energy_ev / EV_PER_HA

            gradient_ha_bohr = None
            if deriv_order >= 1:
                forces_ev_ang = atoms.get_forces()
                gradient_ha_bohr = -forces_ev_ang * GRAD_CONV

            _write_output(output_file, energy_ha, gradient_ha_bohr)

            with open(msg_file, "w") as fh:
                fh.write(f"ASE calculator completed. Energy = {{energy_ha:.8f}} Ha\\n")

        except Exception:
            import traceback

            with open(msg_file, "w") as fh:
                fh.write(
                    "ERROR in Gaussian External ASE script:\\n"
                    + traceback.format_exc()
                )
            raise


    if __name__ == "__main__":
        main()
    '''
)


class ASEExternalCalculatorScript:
    """
    Generates a Gaussian External script that wraps an arbitrary ASE calculator.

    The generated script is a self-contained Python file that Gaussian calls
    during energy/force evaluations.  It reads Gaussian's External input
    file, runs the specified ASE calculator, and writes the result in
    Gaussian's External output format (energy in Hartree, gradient in
    Hartree/Bohr).

    Two code-generation strategies are supported:

    **Code generation** (preferred, transparent):
        Pass a calculator *class* together with ``calc_kwargs``, or pass a
        calculator *instance* together with ``calc_kwargs``.  The script
        will contain a plain import and instantiation statement that can be
        read and edited.

    **Pickle fallback** (arbitrary instances):
        Pass a calculator *instance* without ``calc_kwargs``.  If the
        calculator does not implement ``todict()``, the instance is
        serialised with :mod:`pickle` and the script loads it at runtime.
        An additional ``<script_name>.pkl`` file is written alongside the
        script.

    Parameters
    ----------
    calculator : type or ASE Calculator instance
        The ASE calculator class **or** an instantiated calculator.
    calc_kwargs : dict, optional
        Keyword arguments passed to the calculator constructor in the
        generated script.  Required when *calculator* is a class.
        When *calculator* is an instance and *calc_kwargs* is omitted,
        the class tries ``calculator.todict()`` and falls back to pickle.
    script_name : str
        Base name for the generated script (without ``.py`` extension).

    Examples
    --------
    Code-generation path (recommended)::

        from mace.calculators import MACECalculator
        script = ASEExternalCalculatorScript(
            MACECalculator,
            calc_kwargs={"model_paths": ["model.model"], "device": "cpu"},
            script_name="run_mace",
        )
        script.write("/path/to/job/dir")

    Pickle path (arbitrary instance)::

        calc = SomeExoticCalculator(param=42)
        script = ASEExternalCalculatorScript(calc, script_name="run_exotic")
        script.write("/path/to/job/dir")
    """

    def __init__(self, calculator, calc_kwargs=None, script_name="ase_calculator"):
        self.script_name = script_name
        self._use_pickle = False
        self._pickle_bytes = None

        if inspect.isclass(calculator):
            if calc_kwargs is None:
                raise ValueError(
                    "calc_kwargs is required when passing a calculator class. "
                    "Provide the constructor arguments as a dict."
                )
            self._calc_module = calculator.__module__
            self._calc_class_name = calculator.__name__
            self.calc_kwargs = calc_kwargs
        else:
            # Instance provided
            self._calc_module = type(calculator).__module__
            self._calc_class_name = type(calculator).__name__
            if calc_kwargs is not None:
                self.calc_kwargs = calc_kwargs
            elif hasattr(calculator, "todict"):
                logger.debug(
                    f"Extracting calculator parameters via "
                    f"{self._calc_class_name}.todict()."
                )
                self.calc_kwargs = calculator.todict()
            else:
                logger.debug(
                    f"No calc_kwargs provided and {self._calc_class_name} "
                    "does not implement todict(); falling back to pickle."
                )
                import pickle

                self._pickle_bytes = pickle.dumps(calculator)
                self._use_pickle = True
                self.calc_kwargs = None

    @property
    def script_filename(self):
        """Filename of the generated script (with .py extension)."""
        name = self.script_name
        return name if name.endswith(".py") else name + ".py"

    def write(self, directory="."):
        """
        Write the external calculator script (and optional pickle file).

        The script is made executable (``chmod +x``).

        Parameters
        ----------
        directory : str
            Directory in which to write the files.

        Returns
        -------
        str
            Absolute path to the written ``.py`` script.
        """
        os.makedirs(directory, exist_ok=True)
        script_path = os.path.join(directory, self.script_filename)
        content = self._generate_script(directory)
        with open(script_path, "w") as fh:
            fh.write(content)
        # Make the script executable
        current = os.stat(script_path).st_mode
        os.chmod(script_path, current | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
        logger.info(f"Wrote Gaussian External script: {script_path}")

        if self._use_pickle:
            pickle_name = self.script_name + ".pkl"
            pickle_path = os.path.join(directory, pickle_name)
            with open(pickle_path, "wb") as fh:
                fh.write(self._pickle_bytes)
            logger.info(f"Wrote calculator pickle: {pickle_path}")

        return os.path.abspath(script_path)

    # ── Private helpers ───────────────────────────────────────────────────

    def _generate_script(self, directory):
        """Return the complete script content as a string."""
        if self._use_pickle:
            return self._generate_pickle_script()
        return self._generate_code_script()

    def _generate_code_script(self):
        """Generate the code-based script (import + instantiation)."""
        calc_import = (
            f"from {self._calc_module} import {self._calc_class_name}"
        )
        calc_init = f"calc = {self._calc_class_name}(**{self.calc_kwargs!r})"
        return _SCRIPT_TEMPLATE.format(
            script_name=self.script_filename,
            calc_import=calc_import,
            calc_init=calc_init,
            calc_class_name=self._calc_class_name,
        )

    def _generate_pickle_script(self):
        """Generate the pickle-based fallback script."""
        pickle_name = self.script_name + ".pkl"
        return _PICKLE_TEMPLATE.format(pickle_name=pickle_name)
