import logging
import os

from chemsmart.io.folder import BaseFolder

logger = logging.getLogger(__name__)


class CRESTFolder(BaseFolder):
    """
    Folder containing all CREST-related output files for postprocessing.

    CREST calculations generate multiple output files in a single directory.
    This class provides methods to locate and access all these files.

    Typical CREST calculation folder structure:
        crest_calculation/
        ├─ *.out                → main CREST output log
        ├─ crest_conformers.xyz → conformer ensemble (sorted by energy)
        ├─ crest_best.xyz       → lowest-energy conformer
        ├─ crest_rotamers.xyz   → rotamer ensemble
        ├─ crest.energies       → energy list for all conformers
        ├─ coord                → TURBOMOLE format input geometry
        ├─ crestopt.log         → optimization trajectory log file (XYZ format)
        ├─ constraints.inp      → distance constraints (if constrained run)
        └─ ...                  → other auxiliary files
    """

    # Files that are commonly generated by CREST calculations
    # Used for stronger validation of CREST calculation directories
    CREST_DIRECTORY_MARKERS = (
        "crest.restart",
        "crest_input_copy.xyz",
        "coord",
        "wbo",
    )

    @property
    def is_crest_calculation_directory(self):
        """
        Check if this folder is a valid CREST calculation directory.

        Uses a two-level validation:
        1. Must contain exactly one CREST output file (*.out with CREST
           keywords)
        2. Must contain at least one common CREST auxiliary file
           (crest.restart, crest_input_copy.xyz, coord, or wbo)

        Returns:
            bool: True if this is a valid CREST calculation directory.
        """
        if self.crest_out_filepath is None:
            return False
        for filename in self.CREST_DIRECTORY_MARKERS:
            filepath = os.path.join(self.folder, filename)
            if os.path.exists(filepath):
                return True
        logger.debug(
            f"Directory {self.folder} has CREST output file but lacks common "
            f"auxiliary files ({', '.join(self.CREST_DIRECTORY_MARKERS)}). "
            f"Not considered a CREST calculation directory."
        )
        return False

    @property
    def crest_out_filepath(self):
        """
        Return the path to the main CREST output file.

        Returns:
            str | None: Path to the CREST output file, or None if not found.
        """
        crest_out = self.get_all_output_files_in_current_folder_by_program(
            program="crest"
        )
        if not crest_out:
            return None
        if len(crest_out) > 1:
            filenames = ", ".join(
                sorted(os.path.basename(path) for path in crest_out)
            )
            raise ValueError(
                f"Multiple CREST main output files found in '{self.folder}': "
                f"{filenames}. Each CREST calculation directory must contain "
                f"exactly one main output file."
            )
        return crest_out[0]

    @property
    def conformers_xyz_filepath(self):
        """Return the path to the conformer ensemble file."""
        conformers_xyz = os.path.join(self.folder, "crest_conformers.xyz")
        return conformers_xyz if os.path.exists(conformers_xyz) else None

    @property
    def best_xyz_filepath(self):
        """Return the path to the best (lowest energy) conformer file."""
        best_xyz = os.path.join(self.folder, "crest_best.xyz")
        return best_xyz if os.path.exists(best_xyz) else None

    @property
    def rotamers_xyz_filepath(self):
        """Return the path to the rotamer ensemble file."""
        rotamers_xyz = os.path.join(self.folder, "crest_rotamers.xyz")
        return rotamers_xyz if os.path.exists(rotamers_xyz) else None

    @property
    def energies_filepath(self):
        """Return the path to the energies file."""
        energies = os.path.join(self.folder, "crest.energies")
        return energies if os.path.exists(energies) else None

    @property
    def constraints_inp_filepath(self):
        """Return the path to the constraints input file."""
        constraints_inp = os.path.join(self.folder, "constraints.inp")
        return constraints_inp if os.path.exists(constraints_inp) else None

    @property
    def crestopt_log_filepath(self):
        """Return the path to optimization trajectory log file."""
        crestopt_log = os.path.join(self.folder, "crestopt.log")
        return crestopt_log if os.path.exists(crestopt_log) else None

    @property
    def coord_filepath(self):
        """Return the path to TURBOMOLE coord file."""
        coord = os.path.join(self.folder, "coord")
        return coord if os.path.exists(coord) else None
