"""Stable slash-command catalog displayed by the chat composer."""

SLASH_PALETTE_COMMANDS: tuple[tuple[str, str], ...] = (
    ("/help", "show available commands"),
    ("/jobs", "open the jobs panel"),
    ("/runs", "open the calculation monitor"),
    ("/queue", "show the current queue snapshot"),
    ("/server", "switch the active HPC server"),
    ("/molecule", "load and preview a molecule"),
    ("/cancel", "cancel a queued or running job"),
    ("/extract", "parse a final result"),
    ("/dryrun", "regenerate the current dry-run"),
    ("/allow", "allow the focused tool request once"),
    ("/allow-session", "allow the focused tool for this session"),
    ("/deny", "deny the focused tool request"),
    ("/permissions", "toggle permission or driving mode"),
    ("/yolo", "toggle risky-tool autonomy"),
    ("/execute", "submit the dry-run to HPC for real"),
    ("/submit", "submit the validated chemsmart sub command"),
    ("/run", "execute the validated chemsmart run command"),
    ("/critic", "show the current critic verdict"),
    ("/plan", "show the current plan"),
    ("/rationale", "show planner rationale"),
    ("/clear", "clear the transcript"),
    ("/sessions", "browse recent sessions"),
    ("/resume", "load or continue a session"),
    ("/tools", "list registered tools"),
    ("/wizard", "probe server setup and render YAML"),
    ("/wizard-refresh", "refresh node cache"),
    ("/wizard-verify", "verify server transport wiring"),
    ("/wizard-write", "write latest wizard YAML"),
    ("/doctor", "run inline diagnostics"),
    ("/init", "create or update the CHEMSMART.md agent rules file"),
    ("/project", "start a project YAML request"),
    ("/write-project", "write or replace the latest validated project YAML"),
    ("/quit", "exit the TUI"),
    ("/exit", "exit the TUI"),
)
