from __future__ import annotations

"""
Staged GROMACS workflow orchestration.

This module connects separate GROMACS jobs into the standard sequence:

    EM -> NVT -> NPT -> MD

Each stage remains an independent GromacsJob. The workflow only manages
dependencies and passes generated structures and checkpoints between stages.
"""

import logging
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Mapping

from chemsmart.jobs.gromacs.job import (
    GromacsEMJob,
    GromacsMDJob,
    GromacsNPTJob,
    GromacsNVTJob,
)

logger = logging.getLogger(__name__)


@dataclass(frozen=True)
class GromacsStageArtifacts:
    """
    Expected files generated by one GROMACS stage.
    """

    name: str
    tpr_file: Path
    structure_file: Path
    checkpoint_file: Path
    log_file: Path


class GromacsWorkflow:
    """
    Run the standard staged GROMACS simulation workflow.

    The workflow creates four independent jobs:

        EM -> NVT -> NPT -> MD

    Structure files are passed after every stage. Checkpoint files are passed
    from NVT to NPT and from NPT to production MD.
    """

    STAGE_ORDER = (
        "em",
        "nvt",
        "npt",
        "md",
    )

    STAGE_JOB_CLASSES = {
        "em": GromacsEMJob,
        "nvt": GromacsNVTJob,
        "npt": GromacsNPTJob,
        "md": GromacsMDJob,
    }

    RESERVED_STAGE_OPTIONS = {
        "label",
        "jobrunner",
        "structure_file",
        "top_file",
        "itp_files",
        "index_file",
        "workflow",
        "checkpoint_file",
    }

    def __init__(
        self,
        *,
        structure_file,
        top_file,
        jobrunner,
        folder,
        itp_files=None,
        index_file=None,
        mdp_files=None,
        stage_options=None,
        skip_completed=False,
    ):
        self.structure_file = Path(structure_file)
        self.top_file = Path(top_file)
        self.jobrunner = jobrunner
        self.folder = Path(folder)

        self.itp_files = [
            Path(path)
            for path in (itp_files or [])
        ]

        self.index_file = (
            Path(index_file)
            if index_file is not None
            else None
        )

        self.mdp_files = {
            stage: Path(path)
            for stage, path in (mdp_files or {}).items()
            if path is not None
        }

        self.stage_options = {
            stage: dict(options)
            for stage, options in (stage_options or {}).items()
        }

        self.skip_completed = skip_completed
        self.jobs = {}

        self._validate_initial_inputs()

    def _validate_initial_inputs(self):
        """
        Validate files required before the workflow starts.
        """
        missing = []

        if not self.structure_file.exists():
            missing.append(str(self.structure_file))

        if not self.top_file.exists():
            missing.append(str(self.top_file))

        for itp_file in self.itp_files:
            if not itp_file.exists():
                missing.append(str(itp_file))

        if self.index_file is not None and not self.index_file.exists():
            missing.append(str(self.index_file))

        for mdp_file in self.mdp_files.values():
            if not mdp_file.exists():
                missing.append(str(mdp_file))

        if missing:
            raise FileNotFoundError(
                "Missing GROMACS workflow input files: "
                + ", ".join(missing)
            )

        self.folder.mkdir(
            parents=True,
            exist_ok=True,
        )

    def artifacts_for(self, stage):
        """
        Return expected output paths for one stage.
        """
        if stage not in self.STAGE_ORDER:
            raise ValueError(
                f"Unsupported GROMACS workflow stage: {stage}"
            )

        stem = self.folder / stage

        return GromacsStageArtifacts(
            name=stage,
            tpr_file=stem.with_suffix(".tpr"),
            structure_file=stem.with_suffix(".gro"),
            checkpoint_file=stem.with_suffix(".cpt"),
            log_file=stem.with_suffix(".log"),
        )

    def _get_stage_options(self, stage):
        """
        Return validated options for one stage.
        """
        options = dict(
            self.stage_options.get(stage, {})
        )

        invalid = (
            self.RESERVED_STAGE_OPTIONS
            .intersection(options)
        )

        if invalid:
            raise ValueError(
                "Reserved GROMACS workflow options cannot be "
                f"overridden for stage {stage}: "
                + ", ".join(sorted(invalid))
            )

        return options

    def _build_stage_job(
        self,
        stage,
        *,
        structure_file,
        checkpoint_file=None,
    ):
        """
        Construct one stage job with dependency inputs attached.
        """
        job_class = self.STAGE_JOB_CLASSES[stage]
        options = self._get_stage_options(stage)

        mdp_file = self.mdp_files.get(stage)

        job = job_class(
            molecule=None,
            label=stage,
            jobrunner=self.jobrunner,
            mdp_file=mdp_file,
            structure_file=structure_file,
            top_file=self.top_file,
            itp_files=self.itp_files,
            index_file=self.index_file,
            checkpoint_file=checkpoint_file,
            workflow="prepared",
            **options,
        )

        # This changes the default TPR path to:
        # workflow_folder/em.tpr, nvt.tpr, npt.tpr or md.tpr.
        job.set_folder(self.folder)

        return job

    @staticmethod
    def _log_finished(log_file):
        """
        Return True when a GROMACS log reports normal mdrun termination.
        """
        if not log_file.exists():
            return False

        content = log_file.read_text(
            encoding="utf-8",
            errors="ignore",
        )

        return "Finished mdrun" in content

    def _stage_completed(self, stage):
        """
        Return True if an existing stage can safely be reused.
        """
        artifacts = self.artifacts_for(stage)

        if not artifacts.structure_file.exists():
            return False

        if not self._log_finished(artifacts.log_file):
            return False

        # These checkpoints are needed by subsequent stages.
        if stage in {"nvt", "npt"}:
            return artifacts.checkpoint_file.exists()

        return True

    def _validate_stage_outputs(self, stage):
        """
        Ensure one stage produced everything required by the next stage.
        """
        artifacts = self.artifacts_for(stage)

        required = [
            artifacts.structure_file,
            artifacts.log_file,
        ]

        if stage in {"nvt", "npt"}:
            required.append(
                artifacts.checkpoint_file
            )

        missing = [
            str(path)
            for path in required
            if not path.exists()
        ]

        if missing:
            raise RuntimeError(
                f"GROMACS stage {stage} did not produce "
                "the required output files: "
                + ", ".join(missing)
            )

        if not self._log_finished(artifacts.log_file):
            raise RuntimeError(
                f"GROMACS stage {stage} did not terminate normally. "
                f"Check {artifacts.log_file}."
            )

        return artifacts

    def run(self):
        """
        Run EM, NVT, NPT and MD sequentially.

        Returns:
            dict[str, GromacsJob]: Jobs keyed by stage name.
        """
        input_structure = self.structure_file
        previous_checkpoint = None

        for stage in self.STAGE_ORDER:
            # EM -> NVT only passes the minimized structure.
            # NVT -> NPT and NPT -> MD also pass the checkpoint.
            checkpoint_file = (
                previous_checkpoint
                if stage in {"npt", "md"}
                else None
            )

            job = self._build_stage_job(
                stage,
                structure_file=input_structure,
                checkpoint_file=checkpoint_file,
            )

            self.jobs[stage] = job

            if (
                self.skip_completed
                and self._stage_completed(stage)
            ):
                logger.info(
                    "Skipping completed GROMACS stage: %s",
                    stage,
                )
            else:
                logger.info(
                    "Running GROMACS workflow stage: %s",
                    stage,
                )
                job.run()

            artifacts = self._validate_stage_outputs(
                stage
            )

            input_structure = (
                artifacts.structure_file
            )

            previous_checkpoint = (
                artifacts.checkpoint_file
            )

        return self.jobs