SERVER:
  SCHEDULER: null
  QUEUE_NAME: null
  NUM_HOURS: 24
  MEM_GB: 8
  NUM_CORES: 2
  NUM_GPUS: 0
  NUM_THREADS: 2
  SCRATCH_DIR: /scratch
  USE_HOSTS: false

PYSCF:
  EXEFOLDER: /opt/conda/bin
  LOCAL_RUN: true
  SCRATCH: false

XTB:
  EXEFOLDER: /opt/conda/bin
  LOCAL_RUN: true
  SCRATCH: true
